### ISSUE TITLE
The 'safe' option is depricated

### ISSUE THREAD

**Issue by egyptianbman** [bobthecow/genghis#149]
"PHP error: MongoCollection::insert(): The 'safe' option is deprecated, please use 'w' instead"

replacing array('safe' => true) with array('w' => true) in remove(), insert() and update() resolves the issue.

**Comment by bobthecow** [comment]
No it's not.

You're using an unreleased (and hence, unsupported) version of the PHP Mongo driver. `safe` _will_ be deprecated in the next release, but they don't even have a beta release out, let alone an RC or a stable release :)

**Comment by bobthecow** [comment]
As is fitting, the fix for a bug with an unreleased version of the driver is to use an unreleased version of Genghis :)

The `develop` branch has had a fix for this for three months or so. Give that version a shot and let me know if it doesn't work for you?

https://github.com/bobthecow/genghis/tree/develop

**Comment by bobthecow** [comment]
Since this has come up more than once (see #137) I've shipped a fix for it in v1.3.9. Update to the latest version of Genghis to get it :)

**Comment by egyptianbman** [comment]
Thank you!
