### ISSUE TITLE
Bug in Genghis.Util.humanizeSize

### ISSUE THREAD

**Issue by thomas-riccardi** [bobthecow/genghis#167]
``` javascript
Genghis.Util.humanizeSize(144.05351170568562)
// result: '1445 Bytes'
```

I found this in the 'Avg. object size' in some collections.

Why is `Genghis.Util.round` so complicated?

**Comment by bobthecow** [comment]
Thank you for reporting this. It has been fixed in v2.3.11.

`Genghis.Util.round` is so complicated because it's poorly named and has to deal with a lot of edge cases :)

The bug was in humanizeSize, though. 

``` js
size = Genghis.Util.round(size, 2).toString().replace(/\.0+/, '');
```

That regex is missing an anchor, so it removes the `.0` in `144.05` and ends up with `1445`.

**Comment by thomas-riccardi** [comment]
Thanks for the quick fix!

**Comment by bobthecow** [comment]
No problem.
