### ISSUE TITLE
Key 'class'

### ISSUE THREAD

**Issue by kdauzickas** [bobthecow/genghis#47]
Rendering weirdness again. Whenever there's a key with a key `class` it gets quoted.

Data: `{class: "foo"}`

Expected render:

```
{
    class: "foo"
}
```

Actual render:

```
{
    "class": "foo"
}
```

**Comment by bobthecow** [comment]
It has to be. Class is a reserved keyword in javascript, so it has to be quoted as a property name.

**Comment by bobthecow** [comment]
A bit more detail:

Because valid JSON sucks to write for humans, Genghis uses a superset of JSON that is almost regular javascript objects. This means it quotes as few property names as possible. Things with spaces, hyphens, and other invalid "variable name" characters will always have to be quoted. So will reserved keywords in javascript, regardless of whether they're currently used by the javascript spec (i.e. `class`).

**Comment by kdauzickas** [comment]
I feel like I'd like to argue more (JSON has no reserved words, yada, yada, yada) but I doubt that there's any better practical solution than what's implemented now

**Comment by bobthecow** [comment]
right. json has no reserved words. you have to double quote _everything_ in json. so that's worse, imo.
