### ISSUE TITLE
Namespaced collection names

### ISSUE THREAD

**Issue by heruan** [bobthecow/genghis#56]
I have collection names organized in namespaces using dot-notation (as suggested in MongoDB [documentation](http://www.mongodb.org/display/DOCS/Collections)). For example, a collection could be named `My.Users.Employees`. When using dotted names, actions like deleting a collection in Genghis fail (e.g. when Genghis asks to explicitly write the collection's name to confirm deletion, it doesn't work). It may be just a JavaScript issue, I'm not sure.
A similar behaviour happens when collection names have a backslash character in them (e.g. `My\Users\Employees`, in PHP namespace notation).

**Comment by bobthecow** [comment]
Thanks for reporting this, I'll take a look.

**Comment by bobthecow** [comment]
I just created a failing test case for this problem. The Ruby backend was fine, but the PHP backend needed help. The test and a fix for PHP are in `develop`. Note that I haven't fixed forward slashes in collection names yet, but it works for all sorts of other crazy characters now. Feel free to use the develop branch version and let me know if you have any other problems. Otherwise, it'll be in the next release.

**Comment by bobthecow** [comment]
Ha! My test case was wrong, forward slashes in URLs works just fine :)

|'m closing this issue, as v2.1.5 was just released. Thanks again for the bug report.
