### ISSUE TITLE
In-place update?

### ISSUE THREAD

**Issue by julien-c** [bobthecow/genghis#57]
Not sure that's doable, but it would be great.

**Comment by bobthecow** [comment]
Meaning a single property update?

**Comment by julien-c** [comment]
Sorry I wasn't clear enough. I mean in-place update of the app itself?

**Comment by bobthecow** [comment]
Hmm. I can see where this would be useful, but I'm leaning toward no.

I assume you mean for the PHP version, because you'd use ruby gems to update the Ruby version…

On a properly configured server, the PHP process shouldn't be able to modify its own source code. Even on an improperly configured server, there are so many things which could go wrong downloading or replacing the file, that I'd rather not risk it.

Even if I could guarantee that I would never break anything or leave a half replaced file, or delete something in the middle of a request or something, I wouldn't want to take responsibility for downloading and installing arbitrary code on other people's machines. Sure, GitHub is generally secure, but what happens if it gets compromised? A malicious person could send out an "update" which automatically downloaded and installed on every server running Genghis, and that wouldn't be awesome.

Let's just stick with "update it yourself" :)
