### ISSUE TITLE
Empty array and object field values are displayed the same

### ISSUE THREAD

**Issue by jmikola** [bobthecow/genghis#7]
This is likely a shortcoming of the PECL driver, not Genghis, but I wanted to run it by you anyway. I have two records in Mongo that have an array and object for a particular field.

```
> db.program.find(ObjectId("4eefe2977cdec12246000474"), {foo:1});
{ "_id" : ObjectId("4eefe2977cdec12246000474"), "foo" : [ ] }
> db.program.find(ObjectId("4f5152f122f0e15429001078"), {foo:1});
{ "_id" : ObjectId("4f5152f122f0e15429001078"), "foo" : { } }
```

Genghis happens to render both instances of `foo` as `[]` when displaying the documents, although MongoDB's JS console will properly differentiate.

**Comment by bobthecow** [comment]
Since PHP has no object literals, really the only way to tell the difference between an "array" and a "hash" is by checking whether the keys of the array are consecutive integers starting with zero. Which is what `json_encode` does to decide whether to show `{}` or `[]`... In this case, it's an empty array so it could go either way.

You can also trick it by creating an object with keys that look like an array: `{foo: {0: 'bar', 1: 'baz'}}` will show up as `{foo: ['bar', 'baz']}`.

The PECL driver is also a bit to blame: This could be overcome if it allowed retrieving documents as `StdClass` instances by default (the way `json_decode` does). Ideally one could insert either objects or associative arrays, and (optionally) retrieve query results as objects.

Incidentally, you can work around this on the `insert` side by passing `StdClass` instances rather than arrays for `{}`. Unfortunately there's no way to retrieve them without getting `[]` back.

Or better yet, they could create a `MongoDocument` class which implements `ArrayAccess`, `Traversable`, etc, and has a `toArray` method, and return nested instances of that. Feel like writing a driver patch? :)

**Comment by bobthecow** [comment]
@jmikola So... Since this is a driver limitation, should I assign this issue to you now? :)

**Comment by bobthecow** [comment]
1. Not in `genghis.rb`:
   
   ![](http://i.imgur.com/ZcIHz.png)
2. Closing as `wontfix` because I don't have time to patch the PECL driver to make it return objects :)
