### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by khalidsalomao** [bobthecow/genghis#70]
Would be nice to protect the aplication with a login page, since the first page is an open list of all server (with its authentications).

It would improve this already great app!

**Comment by bobthecow** [comment]
Nope nope!

While I understand why you'd like it, I wouldn't hold your breath. I'm not in the business of re-inventing user authentication systems, and it's not Genghis' job to protect your infrastructure. :)

If you're using Apache, it's trivial to add HTTP basic auth to your `.htaccess` file and lock down access. It is similarly easy to add authentication through your nginx config.

If you're running Genghis in Ruby, there are a myriad of ways to protect it, and most of them even tie directly into your existing authentication infrastructure (Devise and Warden being great examples). Or even something [as simple as this](https://gist.github.com/ae054146e562d8123a8d).

Because there are so many ways to access Genghis, and because the app itself has no control over how you set it up and configure the environment in which it lives, it is next to impossible for it to actually _guarantee_ security. But if you do it on your end, it's pretty easy.

What I would consider would be a section in the README or the wiki with recipes for securing access to Genghis.

_Side note: the first page doesn't list passwords, so it's still not enough information to log in to secured machines._

_Another note: unless you're setting default servers via environment variables, the list of servers is only available to your browser's session anyway. Other people visiting the Genghis install will only have access to `localhost`._

**Comment by khalidsalomao** [comment]
OK, I was thinking in a simple login page with the same nice look and feel of Genguis... 

But after I read the "Another note", I understood that the servers info are note saved in the server (cookie only). 

If the data is in the client only, no need for the authentication.

Thanks for the explanation!
