### ISSUE TITLE
Objects sometimes displaying as arrays

### ISSUE THREAD

**Issue by taxilian** [bobthecow/genghis#98]
I have an object that looks like this:

{
    '0': 1
}

Genghis is rendering it like this:
[
    1
]

**Comment by bobthecow** [comment]
Because yay PHP!

As far as PHP is concerned, that _is_ an array. Unfortunately there's absolutely nothing Genghis can do about it. Until the Mongo PHP driver supports returning objects as objects instead of associative arrays, the PHP implementation will do this.

[Here's a related ticket](https://jira.mongodb.org/browse/PHP-358) for the `save` version of it, but it has the exact same problem for `find` :-/

Until then: deal with it, or use the Ruby backend.

**Comment by taxilian** [comment]
Yeah, I wondered if it were something like that.  I probably will have to switch to the ruby backend, because that could cause some major problems if I accidentally saved with that...

**Comment by bobthecow** [comment]
I remember testing it back in the day, and I don't think it does cause major problems. IIRC the only case where it could potentially mess things up is when a property is an empty array/object.

**Comment by taxilian** [comment]
It could cause problems for us because our system expects it to be an object; if it's an array things might work most of the time but we'd probably eventually end up with a case where it changed it to something that doesn't fit in a normal js array and suddenly it wouldn't serialize correctly and thus wouldn't save and we'd have no idea why.

**Comment by bobthecow** [comment]
But if it's something that doesn't look like a normal JS array, Genghis would see it as an object anyway, right?

**Comment by taxilian** [comment]
the problem is when Genghis saves it to mongo as a normal JS array and then I need to use it in my node app

**Comment by bobthecow** [comment]
![yay-php](https://f.cloud.github.com/assets/53660/329071/d7aeb6c0-9baa-11e2-9ffc-939d6811c173.png)

**Comment by bobthecow** [comment]
you _could_ solve it by not using `0` as a property name ;)

**Comment by bobthecow** [comment]
![](https://f.cloud.github.com/assets/53660/329098/7a5283b6-9bab-11e2-8ed1-0a08237ba2a2.png)

**Comment by taxilian** [comment]
I'm not using 0, I'm using "0" -- a string.  In our case to use anything else would be ridiculous, since what we're doing is a mapping from the index value '0' on something to a point value. =] Hopefully this won't be an issue for most people, and even for us it should be really edge-casey (that's totally a word, honest), but the following demonstrates the problem if used with a language like node: http://cl.ly/image/3r1R3H1p0u07

It scares me to death that if I'm not paying attention my structure could change in such a subtle but important way when going through genghis on php; this is another reason I boycot php these days =]

I'll just use the ruby version

**Comment by bobthecow** [comment]
Except there's no difference between `0` and `"0"` as an array index in PHP _or_ JS:

![](https://f.cloud.github.com/assets/53660/329107/1ebd5fb6-9bac-11e2-9f7d-1ebeed2304e3.png)

There are plenty of reasons to boycott PHP, but what PHP does in this case is exactly what it should do :)

It's the Mongo driver's fault for conflating associative arrays with objects. This is why `json_decode` gives you StdClass objects by default instead of arrays. Once they get around to implementing that in the Mongo PHP driver, all will be well again.

But yeah, use the Ruby version.

**Comment by bobthecow** [comment]
This is the same issue as #7 (mentioning it so they're linked for posterity)
